language: php

php:
  - 5.4
  - 5.5

env:
  global:
    - PLUGIN_NAME=Task
    - PLUGIN_PATH=Plugin/Task
    - REQUIRE=""
    - DB=mysql
    - CAKE_VERSION=2.4
  matrix:
    - CAKE_VERSION=2.3
    - CAKE_VERSION=2.4
    - CAKE_VERSION=master

matrix:
  include:
    - php: 5.4
      env:
        - COVERALLS=1
    - php: 5.4
      env:
        - PHPCS=1
    - php: 5.4
      env:
        - FOC_VALIDATE=1
        
before_script:
  - git clone https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - ../travis/before_script.sh
  - echo "
    CakePlugin::load('Task', array('bootstrap' => true));
    CakePlugin::load('Serializable');
    Configure::write('Serializable', array(
    'serialize' => function(\$value) {
        return base64_encode(serialize(\$value));
    },
    'unserialize' => function(\$value) {
        return unserialize(base64_decode(\$value));
    }
    ));
    " >> ../cakephp/app/Config/bootstrap.php
  - echo "<?php
    require_once dirname(dirname(__FILE__)) . '/vendor/autoload.php';
    require_once dirname(dirname(dirname(__FILE__))) . '/lib/Cake/Console/ShellDispatcher.php';
    return ShellDispatcher::run(\$argv);" > ../cakephp/app/Console/cake.php
  - mkdir ../Standart/
  - git clone https://github.com/imsamurai/cakephp-codesniffer.git --depth 1 ../Standart/CakePHP
  - ls -l ~/.phpenv/versions/$(phpenv version-name)/share/pyrus/.pear/
  - ls -l ~/.phpenv/versions/$(phpenv version-name)/share/pyrus/
  
script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: im.samuray@gmail.com
